#!/bin/sh
VERSION=`cat version`
docker tag lmsmpris:$VERSION ghcr.io/hifiberry/extension_squeezelite_lmsmpris:$VERSION
docker push ghcr.io/hifiberry/extension_squeezelite_lmsmpris:$VERSION
docker tag squeezelite:$VERSION ghcr.io/hifiberry/extension_squeezelite_squeezelite:$VERSION
docker push ghcr.io/hifiberry/extension_squeezelite_squeezelite:$VERSION
